export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'

export const ADD_INGREDIENT_TO_ORDER = 'ADD_INGREDIENT_TO_ORDER'
export const DEL_INGREDIENT_FROM_ORDER = 'DEL_INGREDIENT_FROM_ORDER'

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT'

export const CREATE_ORDER = 'CREATE_ORDER'
